### ISSUE TITLE
onHide source is not implemented

### ISSUE THREAD

**Issue by yiziz** [jerairrest/reboron#11]
The onHide function is passed a `source` argument to identify which source caused the modal to close.  This is stated in the README and also implemented in the `boron` repo [here](https://github.com/yuanyan/boron/blob/cb6fae904e5eb590c73df0a3c38eb744ef16e426/src/modalFactory.js#L125).  I think it would be good for this repo to also implement such logic.

**Comment by BrandonWade** [comment]
This appears to be an issue from when I was updating the project to use ES6. I'll have a fix out for this in the next couple of days when I have some free time.

**Comment by jerairrest** [comment]
@yiziz This should be resolved in 0.4.5!

Cheers!

**Comment by yiziz** [comment]
@jerairrest @BrandonWade Thanks!
