### ISSUE TITLE
Why re-use React.creatClass

### ISSUE THREAD

**Issue by h-michael** [jerairrest/reboron#3]
Why re-use React.createClass at this [commit](https://github.com/jerairrest/reboron/commit/e706739c0f29a14941c0bbf2abf5cf1e17466f61) ?

**Comment by jerairrest** [comment]
I was just doing baby steps toward rewriting to use classes. :) I'll probably get to refactoring this in the next couple of days.

**Comment by jerairrest** [comment]
This has been fixed in 0.3.2 :)

**Comment by h-michael** [comment]
Thanks for your work.
